name: mirror-main-branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror-main-branch:
    runs-on: ubuntu-22.04
    steps:
      - uses: zofrex/mirror-branch@v1
        with:
          target-branch: humble
